### ISSUE TITLE
wechaty无法安装，如图所示

### ISSUE THREAD

**Issue by 2563411574** [bigbrother666sh/shezhangbujianle#2]
![1MXXEGN6FZGM TF9O2AX10F](https://user-images.githubusercontent.com/42865393/161245361-da03061c-8773-4baf-87c7-0933d6cab458.png)

PS C:\Users\Administrator\Desktop\shezhangbujianle-main> pip --default-timeout=100 install wechaty~=0.8 -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

Looking in indexes: http://pypi.douban.com/simple/
Collecting wechaty~=0.8
  Downloading http://pypi.doubanio.com/packages/f5/ab/5913a71bf7b495593f921a3a2238c9c5ecbdc877a8ec76119f71e80e63f6/wechaty-0.8.35-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 2.0 MB/s            
Collecting qrcode
  Downloading http://pypi.doubanio.com/packages/94/9f/31f33cdf3cf8f98e64c42582fb82f39ca718264df61957f28b0bbb09b134/qrcode-7.3.1.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 3.2 MB/s
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package qrcode produced metadata for project name unknown. Fix your #egg=qrcode fragments.
WARNING: Discarding http://pypi.doubanio.com/packages/94/9f/31f33cdf3cf8f98e64c42582fb82f39ca718264df61957f28b0bbb09b134/qrcode-7.3.1.tar.gz#sha256=375a6ff240ca9bd41adc
070428b5dfc1dcfbb0f2507f1ac848f6cded38956578 (from http://pypi.doubanio.com/simple/qrcode/) (requires-python:>=3.6). Requested unknown from http://pypi.doubanio.com/pac
kages/94/9f/31f33cdf3cf8f98e64c42582fb82f39ca718264df61957f28b0bbb09b134/qrcode-7.3.1.tar.gz#sha256=375a6ff240ca9bd41adc070428b5dfc1dcfbb0f2507f1ac848f6cded38956578 (from wechaty~=0.8) has inconsistent name: filename has 'qrcode', but metadata has 'unknown'
  Downloading http://pypi.doubanio.com/packages/12/a5/657b4e6323ddb0f3e25ae9295ac424cfa164b68d9bdd48f86344bea8348e/qrcode-7.3.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 1.7 MB/s            
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package qrcode produced metadata for project name unknown. Fix your #egg=qrcode fragments.
WARNING: Discarding http://pypi.doubanio.com/packages/12/a5/657b4e6323ddb0f3e25ae9295ac424cfa164b68d9bdd48f86344bea8348e/qrcode-7.3.tar.gz#sha256=d72861b65e26b611609f05
47f0febe58aed8ae229d6bf4e675834f40742915b3 (from http://pypi.doubanio.com/simple/qrcode/) (requires-python:>=3.6). Requested unknown from http://pypi.doubanio.com/packa
ges/12/a5/657b4e6323ddb0f3e25ae9295ac424cfa164b68d9bdd48f86344bea8348e/qrcode-7.3.tar.gz#sha256=d72861b65e26b611609f0547f0febe58aed8ae229d6bf4e675834f40742915b3 (from wechaty~=0.8) has inconsistent name: filename has 'qrcode', but metadata has 'unknown'
  Downloading http://pypi.doubanio.com/packages/99/6f/3914ab406164775a6293ebe001e57d23e38c09d51f3909c45bd132684927/qrcode-7.2.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 1.7 MB/s            
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package qrcode produced metadata for project name unknown. Fix your #egg=qrcode fragments.
WARNING: Discarding http://pypi.doubanio.com/packages/99/6f/3914ab406164775a6293ebe001e57d23e38c09d51f3909c45bd132684927/qrcode-7.2.tar.gz#sha256=153ad96f5892e6fe2f3699
296240976ac3a6d068e2eb48bbfc64b4c4c4d675ea (from http://pypi.doubanio.com/simple/qrcode/) (requires-python:>=3.6). Requested unknown from http://pypi.doubanio.com/packa
ges/99/6f/3914ab406164775a6293ebe001e57d23e38c09d51f3909c45bd132684927/qrcode-7.2.tar.gz#sha256=153ad96f5892e6fe2f3699296240976ac3a6d068e2eb48bbfc64b4c4c4d675ea (from wechaty~=0.8) has inconsistent name: filename has 'qrcode', but metadata has 'unknown'
  Downloading http://pypi.doubanio.com/packages/c8/1b/d5e0ad4ca933213fa1491c1038cbcdca14906618b339d29c380f6e3b6d01/qrcode-7.1.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package qrcode produced metadata for project name unknown. Fix your #egg=qrcode fragments.
WARNING: Discarding http://pypi.doubanio.com/packages/c8/1b/d5e0ad4ca933213fa1491c1038cbcdca14906618b339d29c380f6e3b6d01/qrcode-7.1.tar.gz#sha256=59ba630fa2adb637b06571
e6ceec1bb0ecf372c458c4447ceba763061bd3af72 (from http://pypi.doubanio.com/simple/qrcode/) (requires-python:>=3.6). Requested unknown from http://pypi.doubanio.com/packa
ges/c8/1b/d5e0ad4ca933213fa1491c1038cbcdca14906618b339d29c380f6e3b6d01/qrcode-7.1.tar.gz#sha256=59ba630fa2adb637b06571e6ceec1bb0ecf372c458c4447ceba763061bd3af72 (from wechaty~=0.8) has inconsistent name: filename has 'qrcode', but metadata has 'unknown'
  Downloading http://pypi.doubanio.com/packages/c9/03/75dc9218def6be81ba1f75a37ac389b86fd91c98d9709fdaa435f0a3d2b5/qrcode-7.0.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package qrcode produced metadata for project name unknown. Fix your #egg=qrcode fragments.
WARNING: Discarding http://pypi.doubanio.com/packages/c9/03/75dc9218def6be81ba1f75a37ac389b86fd91c98d9709fdaa435f0a3d2b5/qrcode-7.0.tar.gz#sha256=963046df808fbcc9f28200
108ce235128921af225302145238981913705ecaff (from http://pypi.doubanio.com/simple/qrcode/) (requires-python:>=3.6). Requested unknown from http://pypi.doubanio.com/packa
ges/c9/03/75dc9218def6be81ba1f75a37ac389b86fd91c98d9709fdaa435f0a3d2b5/qrcode-7.0.tar.gz#sha256=963046df808fbcc9f28200108ce235128921af225302145238981913705ecaff (from wechaty~=0.8) has inconsistent name: filename has 'qrcode', but metadata has 'unknown'
  Downloading http://pypi.doubanio.com/packages/42/87/4a3a77e59ab7493d64da1f69bf1c2e899a4cf81e51b2baa855e8cc8115be/qrcode-6.1-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: requests in c:\program files\python36\lib\site-packages (from wechaty~=0.8) (2.27.1)
Collecting quart
  Downloading http://pypi.doubanio.com/packages/73/58/ed4352f0a6cd1bf044a76529d1eb058fd714771554d58a8452f623553836/Quart-0.6.15-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 871 kB/s            
Collecting lxml
  Downloading http://pypi.doubanio.com/packages/e7/fe/5daa09273e5e82aad08d8fa0bd28f676bc20fb2cc54d07c6d1b7b4c462b1/lxml-4.8.0-cp36-cp36m-win_amd64.whl (3.7 MB)
     |████████████████████████████████| 3.7 MB 6.4 MB/s            
Collecting wechaty-puppet-service>=0.8.4
  Downloading http://pypi.doubanio.com/packages/8f/ef/cd5ef5dc9237820c31f6f90283e02ca3fe6a057e43072ba6599ba46bbb4a/wechaty_puppet_service-0.8.8-py3-none-any.whl (17 kB)
Collecting wechaty-puppet>=0.3.dev10
  Downloading http://pypi.doubanio.com/packages/7c/93/373eef9629b26c0c0b274f0980258331c82884d52de4f7b2670217307c8f/wechaty_puppet-0.4.1-py3-none-any.whl (31 kB)
Collecting pyee
  Downloading http://pypi.doubanio.com/packages/c7/54/10695d113f03688d79d24bbd7eca30b0e386cbc6d2743ffb68dcae131bf6/pyee-9.0.4-py2.py3-none-any.whl (14 kB)
Collecting wechaty-grpc~=0.20.19
  Downloading http://pypi.doubanio.com/packages/08/7a/c41e73344bdd63b7d7decf5f3f99107c477987d29e8f5520f5c32df2d42b/wechaty_grpc-0.20.19-py3-none-any.whl (23 kB)
Collecting ping3
  Downloading http://pypi.doubanio.com/packages/b5/82/60a4ff2e86b38e2689be8f578b48e928b1c2af6b9e0d70045fa127d13fad/ping3-4.0.0-py3-none-any.whl (13 kB)
Requirement already satisfied: typing-extensions in c:\program files\python36\lib\site-packages (from pyee->wechaty~=0.8) (4.1.1)
Requirement already satisfied: six in c:\program files\python36\lib\site-packages (from qrcode->wechaty~=0.8) (1.16.0)
Requirement already satisfied: colorama in c:\program files\python36\lib\site-packages (from qrcode->wechaty~=0.8) (0.4.4)
Requirement already satisfied: jinja2 in c:\program files\python36\lib\site-packages (from quart->wechaty~=0.8) (3.0.3)
Requirement already satisfied: click in c:\program files\python36\lib\site-packages (from quart->wechaty~=0.8) (8.0.4)
Requirement already satisfied: itsdangerous in c:\program files\python36\lib\site-packages (from quart->wechaty~=0.8) (2.0.1)
Requirement already satisfied: multidict in c:\program files\python36\lib\site-packages (from quart->wechaty~=0.8) (5.2.0)
Collecting hypercorn<0.6,>=0.4
  Downloading http://pypi.doubanio.com/packages/16/4d/957597a7be5a9feb3ef60073b061b83b57447b80bcf482c99f5f050ce862/Hypercorn-0.5.4-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 3.2 MB/s            
Collecting aiofiles
  Downloading http://pypi.doubanio.com/packages/ca/e4/b78d049f7cc7ed053ddbfdd59b2dcc7bd387458e2c2869b602975685d65e/aiofiles-0.8.0-py3-none-any.whl (13 kB)
Collecting sortedcontainers
  Downloading http://pypi.doubanio.com/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting blinker
  Downloading http://pypi.doubanio.com/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz (111 kB)
     |████████████████████████████████| 111 kB ...
  Preparing metadata (setup.py) ... done
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\program files\python36\lib\site-packages (from requests->wechaty~=0.8) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\program files\python36\lib\site-packages (from requests->wechaty~=0.8) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python36\lib\site-packages (from requests->wechaty~=0.8) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python36\lib\site-packages (from requests->wechaty~=0.8) (3.3)
Requirement already satisfied: h2>=3.1.0 in c:\program files\python36\lib\site-packages (from hypercorn<0.6,>=0.4->quart->wechaty~=0.8) (4.1.0)
Requirement already satisfied: h11 in c:\program files\python36\lib\site-packages (from hypercorn<0.6,>=0.4->quart->wechaty~=0.8) (0.13.0)
Collecting wsproto>=0.14.0
  Downloading http://pypi.doubanio.com/packages/ea/25/0934b1d00f404d75335b144d4396e01998f25db8953bf54b4d6fe65b80ab/wsproto-1.0.0-py3-none-any.whl (24 kB)
Collecting pytoml
  Downloading http://pypi.doubanio.com/packages/a5/47/c7f8a0f210ad18576840922e0b504f0b7f5f73aea4a52ab14c5b58517edf/pytoml-0.1.21-py2.py3-none-any.whl (8.5 kB)
Collecting betterproto
  Using cached betterproto-1.2.5-py3-none-any.whl
Requirement already satisfied: grpclib in c:\program files\python36\lib\site-packages (from wechaty-grpc~=0.20.19->wechaty-puppet-service>=0.8.4->wechaty~=0.8) (0.4.2)
Requirement already satisfied: importlib-metadata in c:\program files\python36\lib\site-packages (from click->quart->wechaty~=0.8) (4.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\program files\python36\lib\site-packages (from jinja2->quart->wechaty~=0.8) (2.0.1)
Requirement already satisfied: hpack<5,>=4.0 in c:\program files\python36\lib\site-packages (from h2>=3.1.0->hypercorn<0.6,>=0.4->quart->wechaty~=0.8) (4.0.0)
Requirement already satisfied: hyperframe<7,>=6.0 in c:\program files\python36\lib\site-packages (from h2>=3.1.0->hypercorn<0.6,>=0.4->quart->wechaty~=0.8) (6.0.1)
Requirement already satisfied: dataclasses in c:\program files\python36\lib\site-packages (from wsproto>=0.14.0->hypercorn<0.6,>=0.4->quart->wechaty~=0.8) (0.8)
Collecting backports-datetime-fromisoformat
  Downloading http://pypi.doubanio.com/packages/20/15/4bc39da78d00da480ff627398ad25770be1f0c3cf40ea9bc5e9030b441fb/backports-datetime-fromisoformat-1.0.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: stringcase in c:\program files\python36\lib\site-packages (from betterproto->wechaty-grpc~=0.20.19->wechaty-puppet-service>=0.8.4->wechaty~=0.8) (1.2.0)
Requirement already satisfied: zipp>=0.5 in c:\program files\python36\lib\site-packages (from importlib-metadata->click->quart->wechaty~=0.8) (3.6.0)
Using legacy 'setup.py install' for blinker, since package 'wheel' is not installed.
Using legacy 'setup.py install' for backports-datetime-fromisoformat, since package 'wheel' is not installed.
Installing collected packages: backports-datetime-fromisoformat, wsproto, pytoml, betterproto, wechaty-grpc, sortedcontainers, qrcode, pyee, ping3, hypercorn, blinker, aiofiles, wechaty-puppet-service, wechaty-puppet, quart, lxml, wechaty
    Running setup.py install for backports-datetime-fromisoformat ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-h6ccj4mr\\backports-
datetime-fromisoformat_7d7883d8050f41ef85daa3f6e5724803\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-h6ccj4mr\\backports-datetime-fromisoformat_7d7883d8050f
41ef85daa3f6e5724803\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.rea
d().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-vhrnuqyu\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python36\Include\backports-datetime-fromisoformat'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-h6ccj4mr\backports-datetime-fromisoformat_7d7883d8050f41ef85daa3f6e5724803\
    Complete output (28 lines):
    running install
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-ins    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-ins    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-h6ccj4mr\\backports-datetime-fromisoformat_7d7883d8050f41ef85daa3f6e5724803\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-h6ccj4mr\\backports-datetime-fromisoformat_7d7883d8050f41ef85daa3f6e5724803\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');cod    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-ins    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-ins    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-h6ccj4mr\\backports-datetime-fromisoformat_7d7883d8050f41ef85daa3f6e5724803\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-h6ccj4mr\\backports-datetime-fromisoformat_7d7883d8050f41ef85daa3f6e5724803\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-vhrnuqyu\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python36\Include\backports-datetime-fromisoformat' Check the logs for full command output.

**Comment by wj-Mcat** [comment]
According to your erro log info, it should the  the version error: 

* python 3.7 +
* the latest setuptools 

So, the following command is suggested to install wechaty related package:

```shell
# create new virtual env
conda create -n wechaty python=3.7

# install wechaty 
pip install wechaty wechaty-puppet-service
```

Hope that can help you fix your problem.
