### ISSUE TITLE
想完整体验整个项目

### ISSUE THREAD

**Issue by frank-pian** [bigbrother666sh/shezhangbujianle#4]
我看到安装教程只有node相关的,python相关有依赖包和启动设置说明么？
万分感谢

**Comment by bigbrother666sh** [comment]
https://github.com/wechaty/python-wechaty-getting-started
wechaty的安装还是有一点麻烦的，可以从这里开始

**Comment by bigbrother666sh** [comment]
敬请关注，7~8月期间，会有一次B站直播
