### ISSUE TITLE
不知道是否有demo可以直接实验测试一下

### ISSUE THREAD

**Issue by Amuletter** [bigbrother666sh/shezhangbujianle#5]
感觉是一个非常好的项目，但不是在wechaty中报错就是在npm 安装中报错，导致最终无法实际体验一下o(╥﹏╥)o

**Comment by bigbrother666sh** [comment]
https://github.com/wechaty/python-wechaty-getting-started
wechaty的安装还是有一点麻烦的，可以从这里开始
